# Generated by Django 4.2.11 on 2024-05-22 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SampleNameGen', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submission',
            new_name='Sample',
        ),
    ]
