# Generated by Django 4.2.11 on 2024-07-12 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SampleNameGen', '0002_rename_submission_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sample',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_name',
            field=models.CharField(max_length=100),
        ),
    ]
